# Generated by Django 2.0 on 2020-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200204_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
