# Generated by Django 2.0 on 2020-02-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
