# Generated by Django 2.0 on 2020-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=256)),
                ('focus_cities', models.TextField(default='[]')),
                ('focus_constellations', models.TextField(default='[]')),
                ('focus_stocks', models.TextField(default='[]')),
            ],
        ),
    ]
